version: 2

models:
  - name: fct_messages
    description: "Fact table containing one row per Telegram message with metrics."
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_key
        tests:
          - relationships:
            arguements:
              to: ref('dim_channels')
              field: channel_key

  - name: dim_channels
    description: "Dimension table for Telegram channels."
    columns:
      - name: channel_key
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension for temporal analysis."
    columns:
      - name: date_key
        tests:
          - unique
          - not_null
